language: python
python: "2.7"

cache:
  - pip
  - directories:
    - $HOME/esp

addons:
  apt:
    packages:
      - libncurses-dev
      - flex
      - bison
      - gperf

env:
  global:
    - TOOLCHAIN=xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
    - IDF_VER=v3.2.2

before_install:
  # https://docs.espressif.com/projects/esp-idf/en/stable/get-started/index.html
  - mkdir -p $HOME/esp
  - pushd $HOME/esp
  - wget https://dl.espressif.com/dl/$TOOLCHAIN
  - tar -xzf $TOOLCHAIN
  - export PATH=$PATH:$HOME/esp/xtensa-esp32-elf/bin
  - git clone --depth=1 -b $IDF_VER --recursive https://github.com/espressif/esp-idf.git
  - popd
  - export IDF_PATH=$HOME/esp/esp-idf

install:
  - pip install -r $IDF_PATH/requirements.txt

script:
  - make -j2
